# Task 1: Algorithm Implementation

In [1]:
import random
import numpy as np

# Grid Creation

In [2]:
row = int(input("Enter number of Rows "))
column = int(input("enter number of Columns "))
grid = np.random.randint(0,9, size=(column,row), dtype=int)
grid[0][0] = 0
print(grid)

[[0 8 4 7 7 1 1 1 2 1]
 [0 6 6 7 0 1 3 8 6 5]
 [0 2 7 6 7 5 3 0 5 6]
 [5 5 4 7 2 0 3 2 7 8]
 [8 3 4 7 6 1 2 3 4 2]
 [5 4 1 6 8 6 3 7 8 8]
 [3 7 2 1 7 2 2 2 1 7]
 [5 6 7 4 3 3 7 1 4 6]
 [8 2 4 6 5 2 3 7 0 2]
 [4 8 1 5 3 3 2 5 3 7]]


# Baseline Algorithm

In [3]:
x= int(0)
y= int(0)
finalx = int(row-1)
finaly= int(column-1)
timeSpent= []

In [4]:
while x != finaly and y != finalx:
    down = y+1
    right = x +1
    downPos = grid [down][x]
    rightPos = grid[y][right] 
        
    if rightPos <= downPos :
        x += 1
        timeSpent.append(rightPos)
    elif downPos < rightPos:
        y += 1
        timeSpent.append(downPos)

if x == finalx:
    while y != finaly:
        y += 1
        timeSpent.append(grid[x][y])
elif y == finaly:
    while x != finalx:
        x += 1
        timeSpent.append(grid[x][y])

print("Path takes:\n", timeSpent, "\nTime Consumed is:\n" ,sum(timeSpent) )

Path takes:
 [0, 0, 2, 5, 3, 4, 1, 2, 1, 4, 3, 3, 2, 3, 2, 6, 2, 7] 
Time Consumed is:
 50


# Dijkstra's Algortihm

In [5]:
arrayLenght = len(grid.flatten())
infinity = 999999
SD = list(np.full(arrayLenght, infinity))
predecessor = [0 for i in range(arrayLenght)]
graph = list(grid.flatten())
unvisited= list(grid.flatten())
SD[0] = 0
pos = 0

In [6]:
c1 = [0]
c2 = [finalx]
c3 = [arrayLenght - row]
c4 = [arrayLenght - 1]
top = [x for x in range(1, finalx)]
bottom =[x for x in range((finalx * column)+1, arrayLenght-1)]
left= [x  for x in range(1, finalx * column) if x % row == 0]
right = np.arange(start=finalx + row, stop=arrayLenght - row, step=column)

print("Top Indexes: ", top)
print("Bottom Indexes: ", bottom)
print("Left Indexes: ", left)
print("Right Indexes: ", right)

Top Indexes:  [1, 2, 3, 4, 5, 6, 7, 8]
Bottom Indexes:  [91, 92, 93, 94, 95, 96, 97, 98]
Left Indexes:  [10, 20, 30, 40, 50, 60, 70, 80]
Right Indexes:  [19 29 39 49 59 69 79 89]


In [7]:
def update( pos, minNode):
    try:
        if graph[pos] + SD[minNode] < SD[pos]:
            SD[pos] = graph[pos] + SD[minNode]
            predecessor[pos] = graph[minNode]
    except IndexError:
        print("out of index")

In [8]:
while len(unvisited) != 0:   
    if pos in c1:
        update(pos +1, pos) #R
        update(pos + row, pos)#D
    elif pos in c2:
         update(pos -1, pos)#L
         update(pos + row, pos)#D
    elif pos in c3:
         update(pos - row, pos)#U
         update(pos +1, pos) #R
    elif pos in c4:
         update(pos -row, pos)#U
         update(pos -1, pos)#L
    elif pos in top:
         update(pos + row, pos)#D
         update(pos +1, pos) #R
         update(pos -1, pos)#L
    elif pos in bottom:
         update(pos -row, pos)#U
         update(pos +1, pos) #R
         update(pos -1, pos)#L
    elif pos in left:
         update(pos -row, pos)#U
         update(pos + row, pos)#D
         update(pos +1, pos) #R
    elif pos in right:
         update(pos -row, pos)#U
         update(pos + row, pos)#D
         update(pos -1, pos)#L
    else:
        update(pos +1, pos) #R
        update(pos + row, pos)#D
        update(pos -1, pos)#L
        update(pos -row, pos)#U
    
    unvisited.pop(0)
    pos = pos +1

predecessor = np.array(predecessor)
SD = np.array(SD)
print("Time taken: ", SD[arrayLenght-1])
print("Predecessor Grid: \n",predecessor.reshape((row,column)))
print("Short Distance Grid: \n ",SD.reshape((row,column)))

Time taken:  44
Predecessor Grid: 
 [[0 0 8 4 7 1 3 1 1 2]
 [0 0 6 6 7 0 1 3 2 1]
 [0 0 2 7 6 1 3 2 0 5]
 [0 2 5 4 7 2 0 3 2 7]
 [5 5 3 4 2 0 1 2 3 4]
 [8 3 4 1 6 1 2 3 4 2]
 [5 4 1 2 1 7 3 2 2 1]
 [3 7 2 1 4 3 2 2 1 4]
 [5 6 7 4 3 3 2 1 4 0]
 [8 2 4 6 5 2 3 2 0 2]]
Short Distance Grid: 
  [[ 0  8 12 19 26 21 24 29 31 32]
 [ 0  6 12 19 19 20 23 31 37 37]
 [ 0  2  9 15 22 25 26 25 31 37]
 [ 5  7 11 18 20 20 23 25 32 40]
 [13 10 14 21 26 21 23 26 30 32]
 [18 14 15 21 29 27 26 33 38 40]
 [21 21 17 18 25 27 28 30 31 38]
 [26 27 24 22 25 28 35 31 35 41]
 [34 29 28 28 30 30 33 38 35 37]
 [38 37 29 33 33 33 35 40 38 44]]
